export const petList = [
  {
    id: 1,
    name: '小橘',
    sex: '母',
    age: '8个月',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '小橘是一只活泼可爱的橘猫，喜欢和人玩耍，已完成疫苗接种和绝育手术。它来自一个过度繁殖的家庭，现在渴望找到一个温暖的新家。',
  },
  {
    id: 2,
    name: '豆豆',
    sex: '公',
    age: '2岁',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '豆豆是一只温顺的柴犬，性格安静，适合家庭饲养。曾在街头流浪三个月，经救助后健康状况良好。',
  },
  {
    id: 3,
    name: '雪球',
    sex: '母',
    age: '1岁',
    status: '已预约',
    image: '/model/images/petsaving.png',
    description: '雪球是一只白色短毛猫，性格独立但喜欢撒娇。来自一个无法继续饲养的家庭，已接种全套疫苗。',
  },
  {
    id: 4,
    name: '大黄',
    sex: '公',
    age: '3岁',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '大黄是一只金毛犬，性格温和友善，喜欢小孩。原主人因出国无法带走，现寻找有耐心的家庭。',
  },
  {
    id: 5,
    name: '花花',
    sex: '母',
    age: '5个月',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '花花是一只三花猫，充满好奇心，活泼好动。在救助站出生，从小与人类接触，非常亲人。',
  },
  {
    id: 6,
    name: '黑炭',
    sex: '公',
    age: '1岁半',
    status: '已领养',
    image: '/model/images/petsaving.png',
    description: '黑炭是一只全黑短毛猫，已找到爱它的家庭。感谢新主人的爱心！',
  },
  {
    id: 7,
    name: '奶茶',
    sex: '母',
    age: '7个月',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '奶茶是一只奶牛猫，毛色黑白分明，性格温柔，喜欢被抱。从小被遗弃在小区，经志愿者救助后身体健康。',
  },
  {
    id: 8,
    name: '旺财',
    sex: '公',
    age: '4岁',
    status: '已预约',
    image: '/model/images/petsaving.png',
    description: '旺财是一只中华田园犬，忠诚可靠，适合有院子的家庭。已绝育并接种疫苗，等待新家确认中。',
  },
  {
    id: 9,
    name: '芝麻',
    sex: '公',
    age: '6个月',
    status: '待领养',
    image: '/model/images/petsaving.png',
    description: '芝麻是一只虎斑猫，精力旺盛，喜欢玩玩具。适合有时间陪伴它的主人，最好家中已有其他猫咪。',
  },
  {
    id: 10,
    name: '棉花',
    sex: '母',
    age: '2岁',
    status: '已领养',
    image: '/model/images/petsaving.png',
    description: '棉花是一只白色比熊，已找到爱它的家庭。感谢新主人给予她温暖的家！',
  },
];
